from . import pragtech_medical
from . import pragtech_medical_genetics
from . import pragtech_medical_gyneco 
from . import pragtech_medical_inpatient 
from . import pragtech_medical_nursing 
from . import pragtech_medical_icu 
from . import pragtech_medical_imaging 
from . import pragtech_medical_lab
from . import pragtech_medical_invoice
from . import pragtech_medical_lifestyle 
from . import pragtech_medical_pediatrics 
from . import pragtech_medical_service
from . import pragtech_medical_surgery
from . import pragtech_medical_archives
from . import pragtech_medical_socioeconomics 
from . import pragtech_medical_stock
from . import pragtech_medical_veterinary
