from . import chatbot
from . import chatbot_flow
from . import whatsapp_account
from . import message_warning
from . import discuss_channel
from . import whatsapp_message
from . import chatbot_execution_record
from . import res_partner
from . import crm_lead
#from . import utm_campaign
from . import whatsapp_template
from . import whatsapp_account_inherited
from . import calendar_event
from . import whatsapp_quick_response