# -*- coding: utf-8 -*-
{
    'name': "Odoo WhatsApp Interface",
    'description': """This module enables a dedicated WhatsApp interface within the Odoo WhatsApp module, closely mirroring the WhatsApp Web experience. By isolating the WhatsApp channel from the Discuss module, it enhances both user experience and efficiency in customer interactions.""",
    'summary': """This module enables a dedicated WhatsApp interface within the Odoo WhatsApp module, closely mirroring the WhatsApp Web experience. By isolating the WhatsApp channel from the Discuss module, it enhances both user experience and efficiency in customer interactions.""",
    'author': 'Odox SoftHub LLP',
    'website': "https://www.odoxsofthub.com",
    'version': '17.0',
    'depends': ['mail','whatsapp'],
    'data': [
        'data/data.xml',
        'views/whatsapp_chat_menu.xml',
        'views/res_config_settings.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'odx_odoo_whatsapp_interface/static/src/js/whatsapp_chat.js',
            'odx_odoo_whatsapp_interface/static/src/js/chat_icon.js',
            'odx_odoo_whatsapp_interface/static/src/js/whatsapp_thread_action.js',
            'odx_odoo_whatsapp_interface/static/src/js/thread_model_patch.js',
            'odx_odoo_whatsapp_interface/static/src/js/whatsapp_discuss_container.js',
            'odx_odoo_whatsapp_interface/static/src/js/whatsapp_discuss_sidebar.js',
            'odx_odoo_whatsapp_interface/static/src/js/notification_item_patch.js',
            'odx_odoo_whatsapp_interface/static/src/js/messaging_menu_patch.js',
            'odx_odoo_whatsapp_interface/static/src/js/chat_window_patch.js',
            'odx_odoo_whatsapp_interface/static/src/css/color.css',
            'odx_odoo_whatsapp_interface/static/src/xml/discuss_chat.xml',
            'odx_odoo_whatsapp_interface/static/src/xml/user_message_view.xml',
            'odx_odoo_whatsapp_interface/static/src/xml/channel_invisible.xml',
            'odx_odoo_whatsapp_interface/static/src/xml/message_patch_inherit.xml',
            'odx_odoo_whatsapp_interface/static/src/xml/chat_icon_navbar.xml',
            'odx_odoo_whatsapp_interface/static/src/xml/thread_patch.xml',
        ],
    },
    'images': ['static/description/thumbnail.gif'],
    'category': 'Extra Tools',
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 40,
    'currency': 'USD',
}
